modLoader="javafml" 
loaderVersion="[28,)"
issueTrackerURL="https://github.com/owmii/Lollipop/issues"

[[mods]]
modId="lollipop"
version="${file.jarVersion}"
displayName="Lollipop"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lollipop"
authors="zeroneye"
description='''
A Library mod.
'''

[[dependencies.lollipop]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.107,)"
    ordering="NONE"
    side="BOTH"