modLoader="javafml" 
loaderVersion="[27,)"

[[mods]]
modId="lollipop"
version="${file.jarVersion}"
displayName="Lollipop"
authors="xieao"
description='''
A Library mod.
'''

[[dependencies.lollipop]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.39,)"
    ordering="NONE"
    side="BOTH"